### változók
@protocol = http://
@hostname = localhost
@port = 8000
@host = {{protocol}}{{hostname}}:{{port}}

# LOGIN

### login
# @name login
POST {{host}}/api/users/login 
Accept: application/json
Content-Type: application/json

{
    "positionId": 1,
    "email": "test@example.com",
    "password": "1234567"
}
###
@token = {{login.response.body.data.token}}
### logout user
POST  {{host}}/api/users/logout
Accept: application/json
Authorization: Bearer {{token}}

# USERS

### get users
GET  {{host}}/api/users
Accept: application/json
Authorization: Bearer {{token}}

### get user by id
GET  {{host}}/api/users/4
Accept: application/json
Authorization: Bearer {{token}}

### post user
POST {{host}}/api/users 
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "name":  "test2",
    "email": "test2@example.com",
    "password": "123"
}

### patch user
PATCH {{host}}/api/users/5
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}

{
    "password": "1234"
}

### delete user
DELETE {{host}}/api/users/4
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{token}}


### teszt
get {{host}}/api/


# FILMS

### get films
get {{host}}/api/films
### get films by id
get {{host}}/api/films/1
### post films
POST {{host}}/api/films
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Cica GQ",
    "production": 1951,
    "length": 87,
    "presentation": "1951-09-22",
    "imdbLink": "https://oiiaoiia.org/"
}
### patch films
PATCH {{host}}/api/films/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "Cica mica GQ",
    "production": 1951,
    "length": 87,
    "presentation": "1951-09-22",
    "imdbLink": "https://oiiaoiia.org/"
}


### delete films by id
DELETE {{host}}/api/films/3

Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

#---------------------------------------
# TASKS

### get tasks
get {{host}}/api/tasks
### get tasks by id
get {{host}}/api/tasks/1
### post tasks
POST {{host}}/api/tasks
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "filmId": 11,
    "personId": 74,
    "roleId": 3,
}
### patch tasks
PATCH {{host}}/api/tasks/1206
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "filmId": 11,
    "personId": 73,
    "roleId": 3,
}
### delete tasks by id
DELETE {{host}}/api/tasks/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

#---------------------------------------
# VIDEOS

### get videos
get {{host}}/api/videos
### get videos by id
get {{host}}/api/videos/1
### post videos
POST {{host}}/api/videos
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "filmId": 20,
    "link": "https://www.imdb.com/title/tt27814427/",
    "embedLink": "https://www.imdb.com/title/tt27814427/",
}
### patch videos
PATCH {{host}}/api/videos/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "filmId": 31,
    "link": "https://www.imdb.com/title/tt27814427/",
    "embedLink": "https://www.imdb.com/title/tt27814427/",
}
### delete videos by id
DELETE {{host}}/api/videos/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

#---------------------------------------
# PEOPLE

### get people
get {{host}}/api/people
### get people by id
get {{host}}/api/people/1
### post people
POST {{host}}/api/people
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Kicsi Pétere",
    "gender": 1,
    "photo": "kicsi_petere.jpg",
    "imdbLink": "https://oiiaoiia.org/"
}
### patch people
PATCH {{host}}/api/people/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Tompa Béla",
    "gender": 1,
    "photo": "tompa_bela.jpg",
    "imdbLink": "https://"
}
### delete people by id
DELETE {{host}}/api/people/1
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

#---------------------------------------

# POSITIONS 

### get positions
get {{host}}/api/positions

# FAVOURITE

### get favourite
get {{host}}/api/favourites

# ROLE

### get role
get {{host}}/api/roles